#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_RECEIVE_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_RECEIVE_H

int svmsgReceive(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_RECEIVE_H
