#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_CLIENT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_CLIENT_H

int svmsgFileClient(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_CLIENT_H
