#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_CREATE_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_CREATE_H

int svsemCreate(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_CREATE_H
