#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FORK_FILE_SHARING_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FORK_FILE_SHARING_H

int forkFileSharing(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FORK_FILE_SHARING_H
