#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FORK_CHILD_WAIT_PARENT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FORK_CHILD_WAIT_PARENT_H

int forkChildWaitParent(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FORK_CHILD_WAIT_PARENT_H
