#ifndef THE_LINUX_PROGRAMMING_INTERFACE_HANDLING_SIGTSTP_H
#define THE_LINUX_PROGRAMMING_INTERFACE_HANDLING_SIGTSTP_H

int handlingSigtstp(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_HANDLING_SIGTSTP_H
