#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CHILD_STATUS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CHILD_STATUS_H

int childStatus(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CHILD_STATUS_H
