#ifndef THE_LINUX_PROGRAMMING_INTERFACE_THREAD_CLEANUP_H
#define THE_LINUX_PROGRAMMING_INTERFACE_THREAD_CLEANUP_H

int threadCleanup(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_THREAD_CLEANUP_H
