#ifndef THE_LINUX_PROGRAMMING_INTERFACE_MULTI_SIGCHLD_H
#define THE_LINUX_PROGRAMMING_INTERFACE_MULTI_SIGCHLD_H

int multiSigchld(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_MULTI_SIGCHLD_H
