#ifndef THE_LINUX_PROGRAMMING_INTERFACE_PRINT_WAIT_STATUS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_PRINT_WAIT_STATUS_H

void printWaitStatus(const char *, int);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_PRINT_WAIT_STATUS_H
