#ifndef THE_LINUX_PROGRAMMING_INTERFACE_T_SIGWAITINFO_H
#define THE_LINUX_PROGRAMMING_INTERFACE_T_SIGWAITINFO_H

int tSigwaitinfo(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_T_SIGWAITINFO_H
