#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_SETALL_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_SETALL_H

int svsemSetall(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_SETALL_H
