#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CURR_TIME_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CURR_TIME_H

#define BUF_SIZE 1000

int currTime(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CURR_TIME_H
