#ifndef THE_LINUX_PROGRAMMING_INTERFACE_T_DIRBASENAME_H
#define THE_LINUX_PROGRAMMING_INTERFACE_T_DIRBASENAME_H

int tDirBaseName(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_T_DIRBASENAME_H
