#ifndef THE_LINUX_PROGRAMMING_INTERFACE_GETPWNAM_WENT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_GETPWNAM_WENT_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_GETPWNAM_WENT_H

int getpwnamWent(int, char *[]);