#ifndef THE_LINUX_PROGRAMMING_INTERFACE_EXIT_HANDLERS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_EXIT_HANDLERS_H

int exitHandlers(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_EXIT_HANDLERS_H
