#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SHADOW_FUNCTIONS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SHADOW_FUNCTIONS_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SHADOW_FUNCTIONS_H

int shadowFunctions(int, char *[]);