#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_H

int checkPassword(int, char *[]);