#ifndef THE_LINUX_PROGRAMMING_INTERFACE_APPEND_SEEK_SET_H
#define THE_LINUX_PROGRAMMING_INTERFACE_APPEND_SEEK_SET_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_APPEND_SEEK_SET_H

int appendSeekSet(int, char *[]);