#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_SERVER_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_SERVER_H

int fifoSeqnumServer(int, char*[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_SERVER_H
