#ifndef THE_LINUX_PROGRAMMING_INTERFACE_DEMO_TIMERFD_H
#define THE_LINUX_PROGRAMMING_INTERFACE_DEMO_TIMERFD_H

int demoTimerfd(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_DEMO_TIMERFD_H
