#ifndef THE_LINUX_PROGRAMMING_INTERFACE_ITIMERSPEC_FROM_STR_H
#define THE_LINUX_PROGRAMMING_INTERFACE_ITIMERSPEC_FROM_STR_H

#include <time.h>

void itimerspecFromStr(char *, struct itimerspec *);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_ITIMERSPEC_FROM_STR_H
