#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SET_UNSET_ENV_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SET_UNSET_ENV_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SET_UNSET_ENV_H

int setUnsetEnv(int, char *[]);