#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FORK_WHOS_ON_FIRST_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FORK_WHOS_ON_FIRST_H

int forkWhosOnFirst(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FORK_WHOS_ON_FIRST_H
