#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_WRITER_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_WRITER_H

int svshmXfrWriter(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_WRITER_H
