#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CALENDAR_TIME_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CALENDAR_TIME_H

int calendarTime(int, char *[]);

#define SECOND_IN_TROPICAL_YEAR (365.24219 * 24 * 60 * 60)

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CALENDAR_TIME_H

