#ifndef THE_LINUX_PROGRAMMING_INTERFACE_T_SIGALTSTACK_H
#define THE_LINUX_PROGRAMMING_INTERFACE_T_SIGALTSTACK_H

int tSigaltstack(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_T_SIGALTSTACK_H
