#ifndef THE_LINUX_PROGRAMMING_INTERFACE_ATOMIC_APPEND_H
#define THE_LINUX_PROGRAMMING_INTERFACE_ATOMIC_APPEND_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_ATOMIC_APPEND_H

int atomicAppend(int, char *[]);