#ifndef THE_LINUX_PROGRAMMING_INTERFACE_THREAD_MULTIJOIN_H
#define THE_LINUX_PROGRAMMING_INTERFACE_THREAD_MULTIJOIN_H

int threadMultijoin(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_THREAD_MULTIJOIN_H
