#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_READER_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_READER_H

int svshmXfrReader(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVSHM_XFR_READER_H
