#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CREATE_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CREATE_H

int svmsgCreate(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CREATE_H
