#ifndef THE_LINUX_PROGRAMMING_INTERFACE_PRIVILEGE_VERIFY_H
#define THE_LINUX_PROGRAMMING_INTERFACE_PRIVILEGE_VERIFY_H

int privilegeVerify(int, char *[]);
#endif //THE_LINUX_PROGRAMMING_INTERFACE_PRIVILEGE_VERIFY_H
