#ifndef THE_LINUX_PROGRAMMING_INTERFACE_STRERROR_TEST_H
#define THE_LINUX_PROGRAMMING_INTERFACE_STRERROR_TEST_H

int strerrorTest(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_STRERROR_TEST_H
