#ifndef THE_LINUX_PROGRAMMING_INTERFACE_NFTW_DIR_TREE_H
#define THE_LINUX_PROGRAMMING_INTERFACE_NFTW_DIR_TREE_H

int nftwDirTree(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_NFTW_DIR_TREE_H
