#ifndef THE_LINUX_PROGRAMMING_INTERFACE_NONREENTRANT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_NONREENTRANT_H

int nonreentrant(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_NONREENTRANT_H
