#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SIGMASK_LONGJMP_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SIGMASK_LONGJMP_H

int sigmaskLongjmp(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SIGMASK_LONGJMP_H
