#ifndef THE_LINUX_PROGRAMMING_INTERFACE_T_SIGSUSPEND_H
#define THE_LINUX_PROGRAMMING_INTERFACE_T_SIGSUSPEND_H

int tSigsuspend(int, char* []);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_T_SIGSUSPEND_H
