#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CATCH_RTSIGS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CATCH_RTSIGS_H

int catchRtsigs(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CATCH_RTSIGS_H
