#ifndef THE_LINUX_PROGRAMMING_INTERFACE_DEMO_INOTIFY_H
#define THE_LINUX_PROGRAMMING_INTERFACE_DEMO_INOTIFY_H

int demoInotify(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_DEMO_INOTIFY_H
