#ifndef THE_LINUX_PROGRAMMING_INTERFACE_PROCESS_TIME_H
#define THE_LINUX_PROGRAMMING_INTERFACE_PROCESS_TIME_H

int processTime(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_PROCESS_TIME_H
