#ifndef THE_LINUX_PROGRAMMING_INTERFACE_STRTIME_H
#define THE_LINUX_PROGRAMMING_INTERFACE_STRTIME_H

#define SBUF_SIZE 1000

int strtime(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_STRTIME_H
