#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_SERVER_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_SERVER_H

int svmsgFileServer(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_FILE_SERVER_H
