#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_GOOD_INIT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_GOOD_INIT_H

int svsemGoodInit(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVSEM_GOOD_INIT_H
