#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CHQBYTES_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CHQBYTES_H

int svmsgChqbytes(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SVMSG_CHQBYTES_H
