#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FORK_SIG_SYNC_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FORK_SIG_SYNC_H

int forkSigSync(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FORK_SIG_SYNC_H
