#ifndef THE_LINUX_PROGRAMMING_INTERFACE_UGID_FUNCTIONS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_UGID_FUNCTIONS_H

#endif //THE_LINUX_PROGRAMMING_INTERFACE_UGID_FUNCTIONS_H

int ugidFunctions(int, char *[]);
