#ifndef THE_LINUX_PROGRAMMING_INTERFACE_PROCFS_PIDMAX_H
#define THE_LINUX_PROGRAMMING_INTERFACE_PROCFS_PIDMAX_H

int procfsPidmax(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_PROCFS_PIDMAX_H
