#ifndef THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_CAPS_H
#define THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_CAPS_H

int checkPasswordCaps(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_CHECK_PASSWORD_CAPS_H
