#ifndef THE_LINUX_PROGRAMMING_INTERFACE_SIGNALFD_SIGVAL_H
#define THE_LINUX_PROGRAMMING_INTERFACE_SIGNALFD_SIGVAL_H

int signalfdSigval(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_SIGNALFD_SIGVAL_H
