#ifndef THE_LINUX_PROGRAMMING_INTERFACE_PRINT_RLIMIT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_PRINT_RLIMIT_H

int printRlimit(const char *, int);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_PRINT_RLIMIT_H
