#ifndef THE_LINUX_PROGRAMMING_INTERFACE_RLIMIT_NPROC_H
#define THE_LINUX_PROGRAMMING_INTERFACE_RLIMIT_NPROC_H

int rlimitNproc(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_RLIMIT_NPROC_H
