#ifndef THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_CLIENT_H
#define THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_CLIENT_H

int fifoSeqnumClient(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_FIFO_SEQNUM_CLIENT_H
