#ifndef THE_LINUX_PROGRAMMING_INTERFACE_VIEW_SYMLINK_H
#define THE_LINUX_PROGRAMMING_INTERFACE_VIEW_SYMLINK_H

int viewSymlink(int, char *[]);

#endif //THE_LINUX_PROGRAMMING_INTERFACE_VIEW_SYMLINK_H
